### PR TITLE
Remove Faraday connection authorization warnings

### LINKED ISSUE #116: Faraday Warning on `authorization`
When using the latest version of the gem (with an updated version of Faraday), I see several of these messages:

```log
WARNING: `Faraday::Connection#authorization` is deprecated; it will be removed in version 2.0.
While initializing your connection, use `#request(:authorization, ...)` instead.
See https://lostisland.github.io/faraday/middleware/authentication for more usage info.
```

### PR DESCRIPTION
**Pull request by rickychilcott**
Based on my read of https://lostisland.github.io/faraday/middleware/authentication, this should work fine in Faraday 1 and 2

Close #116

### CODE REVIEW

**Comment by jrcasso** [comment]
Applying this as a monkey patch worked for me. Thanks @hieubui149.

**Review by jrcasso — APPROVED** [review]

**Comment by AndersonDev** [comment]
May we have this merged? To much spamming...

**Comment by BenTalagan** [comment]
Hi! This PR does not fix the faraday warning when using acces_token authentication. I have faced the problem today and this is how I fixed it. Would be nice to integrate it to the PR ?

```ruby
module Asana
  module Authentication
    module OAuth2
      class AccessTokenAuthentication
        def configure(connection)
          @token = @token.refresh! if @token.expired?
          connection.params[:access_token] = @token.token
          connection.request :oauth2, { token_type: :param, param_name: 'access_token' }
        end
      end
    end
  end
end
```

**Comment by AndersonDev** [comment]
It's really priority, because I can't use CLI application, because of warnings

**Comment by igor-alexandrov** [comment]
This is not relevant anymore after #152. @jv-asana please close.

**Comment by rickychilcott** [comment]
I’ll close.

**Pull request closed without merging**
