### PR TITLE
Added support for Faraday 2

### PR DESCRIPTION
**Pull request by igor-alexandrov**
This PR adds support for Faraday 2 to `asana` gem (#141).

All specs pass, I've also tested this in my project and everything works well.

Let's discuss.

### CODE REVIEW

**Comment by jv-asana** [comment]
@igor-alexandrov Thank you for sending this PR. Do you also mind updating the [Appraisals](https://github.com/Asana/ruby-asana/blob/master/Appraisals) file. I think the GitHub action builds are failing because of it.

**Comment by igor-alexandrov** [comment]
@jv-asana added two latest `faraday` version to `Appraisals`.

**Review by jv-asana — APPROVED** [review]
LGTM. Thank you for submitting this PR @igor-alexandrov.

**Comment by igor-alexandrov** [comment]
@jv-asana will you also release gem to Rubygems?

**Comment by jv-asana** [comment]
> @jv-asana will you also release gem to Rubygems?

Hi @igor-alexandrov I was going to wait until we update our library with new endpoints but I can go ahead and release it now instead of waiting.

**Comment by igor-alexandrov** [comment]
@jv-asana no reason to rush, release it when you consider the right time to do this.

**Pull request merged**
